#
tap "borkdude/brew"
tap "clojure-lsp/brew"
tap "heroku/brew"

#
cask "adoptopenjdk/openjdk/adoptopenjdk8"
cask "docker"
cask "droplr"
cask "ngrok"

#
brew "awscli"
brew "borkdude/brew/babashka"
brew "clojure-lsp-native"
brew "coreutils"
brew "gnu-sed"
brew "gpg"
brew "grep"
brew "heroku"
brew "hub"
brew "jq"
brew "leiningen"
brew "npm"
brew "postgresql"
brew "readline"
brew "rlwrap"
brew "sassc"
brew "tmux"

mas "1Password", id: 1333542190
