# https://github.com/aclaimant/aclaimant/blob/main/Brewfile
tap "borkdude/brew"
tap "heroku/brew"
tap "homebrew/cask-versions"

#
cask "droplr"

# https://github.com/aclaimant/aclaimant/blob/main/Brewfile
cask "ngrok"
cask "docker" # Docker Desktop
cask "temurin17"
cask "1password/tap/1password-cli"

#
# brew "clojure"
# brew "clojure-lsp"
# brew "npm"

# https://github.com/aclaimant/aclaimant/blob/main/Brewfile
brew "awscli"
brew "borkdude/brew/babashka"
brew "coreutils"
brew "docker-compose"
brew "git"
brew "gnu-sed"
brew "gpg"
brew "grep"
brew "heroku/brew/heroku"
brew "hub"
brew "jq"
brew "leiningen"
brew "node"
brew "postgresql@16"
brew "readline"
brew "ripgrep"
brew "rlwrap"
brew "sassc"
brew "gh"

#
mas "1Password", id: 1333542190
