# Open-source video transcoder available for Linux, Mac, and Windows
brew "handbrake"

# Access DVDs as block devices without the decryption
brew "libdvdcss"

# Adds an OCR text layer to scanned PDF files
brew "ocrmypdf"

# Free and open-source RSS reader
cask "netnewswire"

# Multimedia player
cask "vlc"

mas "1Blocker - Ad Blocker", id: 1365531024
mas "Banktivity", id: 1480779512
mas "Paprika Recipe Manager 3", id: 1303222628
